"""
Base Model Mixins and Common Fields

Provides reusable mixins for data provenance, timestamps, and common patterns.
"""

from datetime import datetime
from enum import Enum as PyEnum
from typing import Any

from geoalchemy2 import Geography, Geometry
from sqlalchemy import DateTime, Enum, Float, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column


# ============================================================================
# DATA STATUS ENUM
# ============================================================================
class DataStatus(str, PyEnum):
    """Classification of data origin and reliability."""

    OBSERVED = "OBSERVED"  # Direct observation from authoritative source
    DERIVED = "DERIVED"  # Calculated from observed data
    MODELLED = "MODELLED"  # Generated by ML model
    ESTIMATED = "ESTIMATED"  # Estimated/interpolated
    ASSUMED = "ASSUMED"  # Assumed value (use with caution)
    SYNTHETIC = "SYNTHETIC"  # Synthetic/simulated (never in production training)


# ============================================================================
# DATA QUALITY ENUM
# ============================================================================
class DataQuality(str, PyEnum):
    """Data quality classification."""

    EXCELLENT = "EXCELLENT"  # High confidence, validated
    GOOD = "GOOD"  # Normal quality
    FAIR = "FAIR"  # Some concerns
    POOR = "POOR"  # Quality issues detected
    UNKNOWN = "UNKNOWN"  # Not assessed


# ============================================================================
# PROVIDER STATUS ENUM
# ============================================================================
class ProviderStatus(str, PyEnum):
    """Data provider availability status."""

    LIVE = "LIVE"  # Currently active and receiving data
    RECENT = "RECENT"  # Data is recent but not real-time
    STALE = "STALE"  # Data is outdated
    UNAVAILABLE = "UNAVAILABLE"  # Provider not accessible
    CONFIGURATION_REQUIRED = "CONFIGURATION_REQUIRED"  # Credentials needed


# ============================================================================
# TIMESTAMP MIXIN
# ============================================================================
class TimestampMixin:
    """Mixin for created_at and updated_at timestamps."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=datetime.utcnow,
        nullable=False,
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=datetime.utcnow,
        onupdate=datetime.utcnow,
        nullable=False,
    )


# ============================================================================
# DATA PROVENANCE MIXIN
# ============================================================================
class DataProvenanceMixin:
    """Mixin for data provenance tracking."""

    source_id: Mapped[str] = mapped_column(String(100), nullable=False, index=True)
    source_name: Mapped[str] = mapped_column(String(255), nullable=False)
    source_url: Mapped[str | None] = mapped_column(Text, nullable=True)

    retrieved_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        index=True,
    )

    published_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        index=True,
    )

    valid_from: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        index=True,
    )

    valid_to: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    data_status: Mapped[DataStatus] = mapped_column(
        Enum(DataStatus),
        nullable=False,
        default=DataStatus.OBSERVED,
        index=True,
    )

    data_quality: Mapped[DataQuality] = mapped_column(
        Enum(DataQuality),
        nullable=False,
        default=DataQuality.UNKNOWN,
    )


# ============================================================================
# GEOSPATIAL MIXIN
# ============================================================================
class GeospatialMixin:
    """Mixin for geographic coordinates."""

    latitude: Mapped[float] = mapped_column(Float, nullable=False)
    longitude: Mapped[float] = mapped_column(Float, nullable=False)

    # PostGIS geography point (uses WGS84 by default)
    location: Mapped[Any] = mapped_column(
        Geography(geometry_type="POINT", srid=4326),
        nullable=False,
    )
